import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

/** Checked in so typecheck can resolve it. Regenerated by next.config.ts before compile. */
export const PUBLISHED_GUIDE_MANIFEST_PATH = path.join(
  process.cwd(),
  "src/lib/guides/published-slugs.generated.ts",
);

/**
 * Published slug for one guide file, or null when it is still a draft.
 * Non-mdx files are ignored. A missing or non-boolean `draft` is an error so
 * the nav cannot disagree with the guide loader.
 */
export function publishedSlugFromMatter(fileName: string, draft: unknown): string | null {
  if (!fileName.endsWith(".mdx")) return null;
  const slug = fileName.slice(0, -".mdx".length);
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    throw new Error(`${fileName}: slug must be lowercase words separated by hyphens`);
  }
  if (typeof draft !== "boolean") {
    throw new Error(`${fileName}: frontmatter draft must be true or false`);
  }
  return draft ? null : slug;
}

/** Published guide slugs, sorted. Reads frontmatter only — not the guide body pipeline. */
export function readPublishedGuideSlugs(
  dir = path.join(process.cwd(), "content", "guides"),
): string[] {
  if (!fs.existsSync(dir)) return [];
  const slugs: string[] = [];
  for (const file of fs.readdirSync(dir)) {
    if (!file.endsWith(".mdx")) continue;
    const raw = fs.readFileSync(path.join(dir, file), "utf8");
    const slug = publishedSlugFromMatter(file, matter(raw).data.draft);
    if (slug) slugs.push(slug);
  }
  slugs.sort();
  return slugs;
}

export function renderPublishedGuideManifest(slugs: readonly string[]): string {
  const body =
    slugs.length === 0
      ? "[]"
      : `[\n${slugs.map((slug) => `  ${JSON.stringify(slug)},`).join("\n")}\n]`;
  return `// Generated from content/guides by next.config.ts. Do not edit.\nexport const publishedGuideSlugs: readonly string[] = ${body};\n`;
}

/** Writes the layout manifest when the published set changes. Returns the slugs. */
export function writePublishedGuideManifest(
  dir = path.join(process.cwd(), "content", "guides"),
): string[] {
  const slugs = readPublishedGuideSlugs(dir);
  const next = renderPublishedGuideManifest(slugs);
  const current = fs.existsSync(PUBLISHED_GUIDE_MANIFEST_PATH)
    ? fs.readFileSync(PUBLISHED_GUIDE_MANIFEST_PATH, "utf8")
    : "";
  if (current !== next) fs.writeFileSync(PUBLISHED_GUIDE_MANIFEST_PATH, next);
  return slugs;
}
