import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

/** Checked in so typecheck can resolve it. Regenerated by next.config.ts before compile. */
export const PUBLISHED_GUIDE_MANIFEST_PATH = path.join(
  process.cwd(),
  "src/lib/guides/published-slugs.generated.ts",
);

export type PublishedGuideRecord = {
  slug: string;
  /** YYYY-MM-DD from `updated` or `date`, or "" when the frontmatter has neither. */
  updated: string;
};

/**
 * Published slug for one guide file, or null when it is still a draft.
 * Non-mdx files are ignored. A missing or non-boolean `draft` is an error so
 * the nav cannot disagree with the guide loader.
 */
export function publishedSlugFromMatter(fileName: string, draft: unknown): string | null {
  if (!fileName.endsWith(".mdx")) return null;
  const slug = fileName.slice(0, -".mdx".length);
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
    throw new Error(`${fileName}: slug must be lowercase words separated by hyphens`);
  }
  if (typeof draft !== "boolean") {
    throw new Error(`${fileName}: frontmatter draft must be true or false`);
  }
  return draft ? null : slug;
}

/** Calendar day for sitemap lastmod. Invalid values are omitted, not fatal. */
export function publishedGuideUpdatedFromMatter(value: unknown): string {
  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    return value.toISOString().slice(0, 10);
  }
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  return "";
}

export function publishedGuideFromMatter(
  fileName: string,
  data: { draft?: unknown; updated?: unknown; date?: unknown },
): PublishedGuideRecord | null {
  const slug = publishedSlugFromMatter(fileName, data.draft);
  if (!slug) return null;
  return {
    slug,
    updated: publishedGuideUpdatedFromMatter(data.updated ?? data.date),
  };
}

/**
 * Published guides, sorted by slug. Reads frontmatter only, so sitemap
 * generation stays off the guide body pipeline.
 */
export function readPublishedGuides(
  dir = path.join(process.cwd(), "content", "guides"),
): PublishedGuideRecord[] {
  if (!fs.existsSync(dir)) return [];
  const guides: PublishedGuideRecord[] = [];
  for (const file of fs.readdirSync(dir)) {
    if (!file.endsWith(".mdx")) continue;
    const raw = fs.readFileSync(path.join(dir, file), "utf8");
    const guide = publishedGuideFromMatter(file, matter(raw).data);
    if (guide) guides.push(guide);
  }
  guides.sort((a, b) => a.slug.localeCompare(b.slug));
  return guides;
}

/** Published guide slugs, sorted. Reads frontmatter only — not the guide body pipeline. */
export function readPublishedGuideSlugs(
  dir = path.join(process.cwd(), "content", "guides"),
): string[] {
  return readPublishedGuides(dir).map((guide) => guide.slug);
}

function renderStringArray(values: readonly string[]): string {
  if (values.length === 0) return "[]";
  return `[\n${values.map((value) => `  ${JSON.stringify(value)},`).join("\n")}\n]`;
}

export function renderPublishedGuideManifest(
  guides: readonly PublishedGuideRecord[],
): string {
  const slugs = renderStringArray(guides.map((guide) => guide.slug));
  const records =
    guides.length === 0
      ? "[]"
      : `[\n${guides
          .map(
            (guide) =>
              `  { slug: ${JSON.stringify(guide.slug)}, updated: ${JSON.stringify(guide.updated)} },`,
          )
          .join("\n")}\n]`;
  return `// Generated from content/guides by next.config.ts. Do not edit.\nexport const publishedGuideSlugs: readonly string[] = ${slugs};\nexport const publishedGuides: readonly { slug: string; updated: string }[] = ${records};\n`;
}

/** Writes the layout manifest when the published set changes. Returns the slugs. */
export function writePublishedGuideManifest(
  dir = path.join(process.cwd(), "content", "guides"),
): string[] {
  const guides = readPublishedGuides(dir);
  const next = renderPublishedGuideManifest(guides);
  const current = fs.existsSync(PUBLISHED_GUIDE_MANIFEST_PATH)
    ? fs.readFileSync(PUBLISHED_GUIDE_MANIFEST_PATH, "utf8")
    : "";
  if (current !== next) fs.writeFileSync(PUBLISHED_GUIDE_MANIFEST_PATH, next);
  return guides.map((guide) => guide.slug);
}
