import type { CatalogStyle } from "./types";

function pair(
  styleId: string,
  index: number,
  altSource: string,
  altResult: string,
): CatalogStyle["examplePairs"][number] {
  return {
    source: `https://picsum.photos/seed/${styleId}-ex-source-${index}/650/800`,
    result: `https://picsum.photos/seed/${styleId}-ex-result-${index}/650/800`,
    altSource,
    altResult,
  };
}

function personDefaults(title: string, category: string, cinematic = false) {
  if (cinematic) {
    return {
      template: `Edit the uploaded portrait into a cinematic photograph. Use the person in the source image as the subject. Preserve their {{preserve}}. Apply soft directional window light, gentle shadow falloff, subtle film grain, and {{mood}} color grading. Replace the background with {{background}}, keeping natural edges around the hair. Keep skin texture realistic. Do not add people, lettering, or logos. Compose for {{ratio}} without cropping important facial features.`,
      description: `Turn a clear portrait into a soft cinematic image with natural window light and a refined film look.`,
    };
  }
  return {
    template: `Edit the uploaded {{subject}} photo into the ${title} look. Use the main subject in the source image as the subject. Preserve {{preserve}}. Apply a refined ${category.toLowerCase()} treatment with {{mood}} color grading. Use {{background}} while keeping natural, accurate edges around the subject. Keep important textures realistic. Do not add people, lettering, or logos. Compose for {{ratio}} without cropping important features.`,
    description: `Turn a clear photo into the ${title} look while preserving recognizable identity.`,
  };
}

const baseDefaults = {
  mood: "Warm neutral",
  background: "Softly blurred interior",
  ratio: "4:5 Portrait",
  keepClothing: true,
  keepPose: true,
};

export const seedStyles: CatalogStyle[] = [
  {
    id: "cinematic-window",
    title: "Cinematic Window Portrait",
    category: "Cinematic",
    subject: "Person",
    intent: "Change lighting",
    requirement: "One photo",
    tool: "ChatGPT Image",
    note: "Works with one clear photo",
    height: 360,
    saved: 486,
    source: "https://picsum.photos/seed/window-portrait-source/900/1100",
    result: "https://picsum.photos/seed/window-cinema-result/900/1100",
    status: "published",
    targetSourcePhoto: "One clear frontal or three-quarter portrait selfie",
    bestSourcePhoto: [
      "One visible face",
      "Good lighting",
      "Face not hidden by hands or objects",
      "Original image should not be blurry",
    ],
    changes: ["Lighting", "Background", "Color mood", "Film texture"],
    stays: [
      "Face and facial proportions",
      "Skin tone",
      "Hairstyle",
      "Expression",
      "Pose",
      "Clothing",
    ],
    ...(() => {
      const d = personDefaults("Cinematic Window Portrait", "Cinematic", true);
      return { description: d.description, promptVariant: {
        id: "cinematic-window-v1",
        version: "1.0.0",
        tool: "ChatGPT Image",
        mode: "Image edit / transform with uploaded photo",
        inputImageCount: 1,
        inputImageRoles: ["source photo"],
        template: d.template,
        defaults: baseDefaults,
        lastVerified: "2026-09-15",
        limitations: [
          "May soften facial freckles or fine texture",
          "Glasses reflections can shift",
          "Group photos are unsupported in this variant",
        ],
      }};
    })(),
    examplePairs: [
      pair("cinematic-window", 1, "Source portrait example 1", "Cinematic result example 1"),
      pair("cinematic-window", 2, "Source portrait example 2", "Cinematic result example 2"),
      pair("cinematic-window", 3, "Source portrait example 3", "Cinematic result example 3"),
    ],
  },
  {
    id: "golden-hour",
    title: "Dreamy Golden Hour",
    category: "Cinematic",
    subject: "Person",
    intent: "Change lighting",
    requirement: "One photo",
    tool: "Gemini",
    note: "Best with outdoor portraits",
    height: 300,
    saved: 402,
    source: "https://picsum.photos/seed/golden-person-source/900/1000",
    result: "https://picsum.photos/seed/golden-hour-result/900/1000",
    status: "published",
    targetSourcePhoto: "Outdoor or near-window portrait with visible face",
    description:
      "Restyle a portrait with warm golden-hour light, soft glow, and a cinematic sunset mood.",
    bestSourcePhoto: [
      "One visible face",
      "Subject not heavily backlit already",
      "Face not hidden",
      "Original image should not be blurry",
    ],
    changes: ["Lighting", "Sky and glow", "Color mood", "Atmosphere"],
    stays: ["Face", "Skin tone", "Hairstyle", "Expression", "Pose", "Clothing"],
    examplePairs: [
      pair("golden-hour", 1, "Source outdoor portrait", "Golden hour result 1"),
      pair("golden-hour", 2, "Source outdoor portrait 2", "Golden hour result 2"),
    ],
    promptVariant: {
      id: "golden-hour-v1",
      version: "1.0.0",
      tool: "Gemini",
      mode: "Image editing with reference photo",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Dreamy Golden Hour", "Cinematic").template,
      defaults: {
        ...baseDefaults,
        mood: "Warm neutral",
        background: "Window-lit studio",
      },
      lastVerified: "2026-09-14",
      limitations: [
        "Indoor flash photos may look less natural",
        "Very dark underexposed faces can lose detail",
      ],
    },
  },
  {
    id: "vintage-film",
    title: "Vintage Film Snapshot",
    category: "Vintage",
    subject: "Group",
    intent: "Artistic restyle",
    requirement: "One photo",
    tool: "ChatGPT Image",
    note: "Works with casual photos",
    height: 410,
    saved: 377,
    source: "https://picsum.photos/seed/friends-source-photo/900/1100",
    result: "https://picsum.photos/seed/vintage-film-result/900/1100",
    status: "published",
    targetSourcePhoto: "Casual group photo with faces visible",
    description:
      "Transform a group photo with the Vintage Film Snapshot look while keeping every person recognizable.",
    bestSourcePhoto: [
      "All faces visible",
      "Even group lighting",
      "Minimal motion blur",
      "People not heavily overlapping",
    ],
    changes: ["Color treatment", "Background mood", "Lighting", "Image texture"],
    stays: ["Faces", "Skin tones", "Hairstyles", "Expressions", "Poses", "Clothing"],
    examplePairs: [
      pair("vintage-film", 1, "Source group photo 1", "Vintage result 1"),
      pair("vintage-film", 2, "Source group photo 2", "Vintage result 2"),
    ],
    promptVariant: {
      id: "vintage-film-v1",
      version: "1.0.0",
      tool: "ChatGPT Image",
      mode: "Image edit / transform with uploaded photo",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Vintage Film Snapshot", "Vintage").template.replace(
        "{{subject}}",
        "group",
      ),
      defaults: { ...baseDefaults, mood: "Soft pastel" },
      lastVerified: "2026-09-12",
      limitations: [
        "Crowded scenes may merge people",
        "Tiny distant faces can lose identity",
      ],
    },
  },
  {
    id: "watercolor-portrait",
    title: "Soft Watercolor Portrait",
    category: "Painting",
    subject: "Person",
    intent: "Artistic restyle",
    requirement: "Photo plus style reference",
    tool: "Other AI editor",
    note: "Works with one visible face",
    height: 320,
    saved: 341,
    source: "https://picsum.photos/seed/watercolor-face-source/900/1050",
    result: "https://picsum.photos/seed/watercolor-art-result/900/1050",
    status: "published",
    targetSourcePhoto: "Clear face portrait plus optional watercolor reference",
    description:
      "Turn a clear portrait into a soft watercolor painting while preserving recognizable facial features.",
    bestSourcePhoto: [
      "One visible face",
      "Good lighting",
      "Face not hidden",
      "Optional style reference ready",
    ],
    changes: ["Art medium", "Background", "Color mood", "Surface texture"],
    stays: ["Face", "Skin tone", "Hairstyle", "Expression", "Pose", "Clothing"],
    examplePairs: [
      pair("watercolor-portrait", 1, "Source face", "Watercolor result 1"),
      pair("watercolor-portrait", 2, "Source face 2", "Watercolor result 2"),
    ],
    promptVariant: {
      id: "watercolor-portrait-v1",
      version: "1.0.0",
      tool: "Other AI editor",
      mode: "Image-to-image with style reference (2 inputs)",
      inputImageCount: 2,
      inputImageRoles: ["source photo", "style reference"],
      template: `${personDefaults("Soft Watercolor Portrait", "Painting").template} If a second style-reference image is provided, match its watercolor paper texture and pigment behavior without copying unrelated subjects.`,
      defaults: { ...baseDefaults, mood: "Soft pastel", background: "Minimal cream wall" },
      lastVerified: "2026-09-10",
      limitations: [
        "Requires a style reference for best results",
        "Fine jewelry detail may dissolve into paint strokes",
      ],
    },
  },
  {
    id: "professional-headshot",
    title: "Studio Professional Headshot",
    category: "Professional portraits",
    subject: "Person",
    intent: "Change background",
    requirement: "One photo",
    tool: "ChatGPT Image",
    note: "Best with a front-facing photo",
    height: 390,
    saved: 620,
    source: "https://picsum.photos/seed/casual-headshot-source/900/1100",
    result: "https://picsum.photos/seed/studio-headshot-result/900/1100",
    status: "published",
    targetSourcePhoto: "Front-facing head-and-shoulders photo",
    description:
      "Restyle a casual portrait into a polished studio headshot with a clean professional background.",
    bestSourcePhoto: [
      "Front-facing face",
      "Shoulders visible",
      "Even lighting preferred",
      "Original image should not be blurry",
    ],
    changes: ["Background", "Lighting", "Color mood", "Studio finish"],
    stays: ["Face", "Skin tone", "Hairstyle", "Expression", "Clothing"],
    examplePairs: [
      pair("professional-headshot", 1, "Casual source", "Studio headshot 1"),
      pair("professional-headshot", 2, "Casual source 2", "Studio headshot 2"),
    ],
    promptVariant: {
      id: "professional-headshot-v1",
      version: "1.0.0",
      tool: "ChatGPT Image",
      mode: "Image edit / transform with uploaded photo",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Studio Professional Headshot", "Professional portraits")
        .template,
      defaults: {
        ...baseDefaults,
        background: "Minimal cream wall",
        keepPose: true,
      },
      lastVerified: "2026-09-16",
      limitations: [
        "Heavy makeup or filters in the source can look unnatural after restyle",
        "Extreme wide-angle selfies may warp proportions",
      ],
    },
  },
  {
    id: "anime-street",
    title: "Anime Street Portrait",
    category: "Anime",
    subject: "Person",
    intent: "Full scene transformation",
    requirement: "One photo",
    tool: "Gemini",
    note: "Works with a clear full-body photo",
    height: 330,
    saved: 533,
    source: "https://picsum.photos/seed/street-person-source/900/1100",
    result: "https://picsum.photos/seed/anime-street-result/900/1100",
    status: "published",
    targetSourcePhoto: "Clear full-body or half-body standing photo",
    description:
      "Transform a clear portrait into an anime street character while preserving identity cues.",
    bestSourcePhoto: [
      "Clear full or half body",
      "Face visible",
      "Simple background preferred",
      "Original image should not be blurry",
    ],
    changes: ["Style treatment", "Background", "Color mood", "Line work"],
    stays: ["Face likeness", "Hairstyle cues", "Expression", "Pose", "Outfit silhouette"],
    examplePairs: [
      pair("anime-street", 1, "Source street portrait", "Anime result 1"),
      pair("anime-street", 2, "Source street portrait 2", "Anime result 2"),
    ],
    promptVariant: {
      id: "anime-street-v1",
      version: "1.0.0",
      tool: "Gemini",
      mode: "Image editing with reference photo",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Anime Street Portrait", "Anime").template,
      defaults: { ...baseDefaults, mood: "Deep blue" },
      lastVerified: "2026-09-13",
      limitations: [
        "Photoreal facial micro-detail will become stylized",
        "Complex busy backgrounds may be reinvented",
      ],
    },
  },
  {
    id: "clay-avatar",
    title: "Clay 3D Avatar",
    category: "3D avatars",
    subject: "Person",
    intent: "Artistic restyle",
    requirement: "One photo",
    tool: "Flux",
    note: "Best with a simple portrait",
    height: 350,
    saved: 298,
    source: "https://picsum.photos/seed/avatar-face-source/900/1000",
    result: "https://picsum.photos/seed/clay-avatar-result/900/1000",
    status: "published",
    targetSourcePhoto: "Simple centered portrait against plain background",
    description:
      "Turn a simple portrait into a clay 3D avatar while keeping the person recognizable.",
    bestSourcePhoto: [
      "Centered face",
      "Simple background",
      "Even lighting",
      "Original image should not be blurry",
    ],
    changes: ["Art medium", "Material", "Background", "Surface texture"],
    stays: ["Face shape", "Hairstyle cues", "Expression", "Proportions"],
    examplePairs: [
      pair("clay-avatar", 1, "Source portrait", "Clay avatar 1"),
      pair("clay-avatar", 2, "Source portrait 2", "Clay avatar 2"),
    ],
    promptVariant: {
      id: "clay-avatar-v1",
      version: "1.0.0",
      tool: "Flux",
      mode: "Image-to-image",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Clay 3D Avatar", "3D avatars").template,
      defaults: { ...baseDefaults, background: "Minimal cream wall" },
      lastVerified: "2026-09-11",
      limitations: [
        "Fine facial asymmetry may be smoothed",
        "Accessories can be simplified into clay forms",
      ],
    },
  },
  {
    id: "forest-explorer",
    title: "Fantasy Forest Explorer",
    category: "Fantasy",
    subject: "Person",
    intent: "New outfit or theme",
    requirement: "One photo",
    tool: "Gemini",
    note: "Works with a standing photo",
    height: 430,
    saved: 455,
    source: "https://picsum.photos/seed/hiker-source-photo/900/1200",
    result: "https://picsum.photos/seed/fantasy-forest-result/900/1200",
    status: "published",
    targetSourcePhoto: "Standing full-body or three-quarter photo",
    description:
      "Place the subject in a fantasy forest explorer look while preserving recognizable identity.",
    bestSourcePhoto: [
      "Standing pose",
      "Face visible",
      "Full or half body",
      "Original image should not be blurry",
    ],
    changes: ["Outfit", "Background", "Lighting", "Atmosphere"],
    stays: ["Face", "Body proportions", "Expression", "Pose"],
    examplePairs: [
      pair("forest-explorer", 1, "Source standing photo", "Forest explorer 1"),
      pair("forest-explorer", 2, "Source standing photo 2", "Forest explorer 2"),
    ],
    promptVariant: {
      id: "forest-explorer-v1",
      version: "1.0.0",
      tool: "Gemini",
      mode: "Image editing with reference photo",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Fantasy Forest Explorer", "Fantasy").template,
      defaults: {
        ...baseDefaults,
        mood: "Deep blue",
        keepClothing: false,
        background: "Window-lit studio",
      },
      lastVerified: "2026-09-09",
      limitations: [
        "Outfit will change by design when clothing toggle is off",
        "Hands holding objects may be reinvented",
      ],
    },
  },
  {
    id: "painted-pet",
    title: "Painted Pet Portrait",
    category: "Pets",
    subject: "Pet",
    intent: "Artistic restyle",
    requirement: "One photo",
    tool: "ChatGPT Image",
    note: "Best with eyes clearly visible",
    height: 315,
    saved: 581,
    source: "https://picsum.photos/seed/pet-source-photo/900/1000",
    result: "https://picsum.photos/seed/painted-pet-result/900/1000",
    status: "published",
    targetSourcePhoto: "Pet close-up with eyes clearly visible",
    description:
      "Turn a clear pet photo into a painted portrait while preserving the animal's recognizable features and expression.",
    bestSourcePhoto: [
      "Eyes clearly visible",
      "Full head in frame",
      "Even lighting on fur",
      "Original image should not be blurry",
    ],
    changes: ["Art medium", "Background", "Color mood", "Surface texture"],
    stays: [
      "Face shape",
      "Fur pattern",
      "Eye color",
      "Expression",
      "Body proportions",
      "Distinctive markings",
    ],
    examplePairs: [
      pair("painted-pet", 1, "Source pet photo", "Painted pet 1"),
      pair("painted-pet", 2, "Source pet photo 2", "Painted pet 2"),
    ],
    promptVariant: {
      id: "painted-pet-v1",
      version: "1.0.0",
      tool: "ChatGPT Image",
      mode: "Image edit / transform with uploaded photo",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Painted Pet Portrait", "Pets").template.replace(
        "{{subject}}",
        "pet",
      ),
      defaults: { ...baseDefaults, mood: "Warm neutral" },
      lastVerified: "2026-09-15",
      limitations: [
        "Multi-pet photos are unsupported in this variant",
        "Very dark fur can lose pattern contrast",
      ],
    },
  },
  {
    id: "travel-postcard",
    title: "Cinematic Travel Postcard",
    category: "Travel",
    subject: "Place",
    intent: "Change lighting",
    requirement: "One photo",
    tool: "Flux",
    note: "Works with landscape photos",
    height: 370,
    saved: 315,
    source: "https://picsum.photos/seed/travel-place-source/900/1000",
    result: "https://picsum.photos/seed/travel-postcard-result/900/1000",
    status: "published",
    targetSourcePhoto: "Landscape or travel scene with a clear focal point",
    description:
      "Restyle a favorite place with cinematic travel-postcard lighting while keeping the scene recognizable.",
    bestSourcePhoto: [
      "Clear focal point",
      "Balanced exposure",
      "Important landmarks visible",
      "Original image should not be blurry",
    ],
    changes: ["Lighting", "Sky and atmosphere", "Color mood", "Surface texture"],
    stays: [
      "Landmarks",
      "Scene layout",
      "Perspective",
      "Main objects",
      "Sense of place",
      "Composition",
    ],
    examplePairs: [
      pair("travel-postcard", 1, "Source travel scene", "Postcard result 1"),
      pair("travel-postcard", 2, "Source travel scene 2", "Postcard result 2"),
    ],
    promptVariant: {
      id: "travel-postcard-v1",
      version: "1.0.0",
      tool: "Flux",
      mode: "Image-to-image",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Cinematic Travel Postcard", "Travel").template.replace(
        "{{subject}}",
        "place",
      ),
      defaults: { ...baseDefaults, mood: "Warm neutral", ratio: "1:1 Square" },
      lastVerified: "2026-09-08",
      limitations: [
        "Tiny signage text may become illegible",
        "Moving clouds/water can be reinterpreted",
      ],
    },
  },
  {
    id: "editorial-fashion",
    title: "Editorial Fashion Look",
    category: "Professional portraits",
    subject: "Person",
    intent: "New outfit or theme",
    requirement: "Photo plus style reference",
    tool: "Other AI editor",
    note: "Best with a full or half-body photo",
    height: 440,
    saved: 267,
    source: "https://picsum.photos/seed/fashion-person-source/900/1200",
    result: "https://picsum.photos/seed/editorial-fashion-result/900/1200",
    status: "published",
    targetSourcePhoto: "Full or half-body portrait plus fashion style reference",
    description:
      "Create an editorial fashion look from a clear portrait while preserving the person's likeness.",
    bestSourcePhoto: [
      "Full or half body",
      "Face visible",
      "Style reference available",
      "Original image should not be blurry",
    ],
    changes: ["Outfit", "Styling", "Background", "Color mood"],
    stays: ["Face", "Body proportions", "Expression", "Pose"],
    examplePairs: [
      pair("editorial-fashion", 1, "Source fashion portrait", "Editorial result 1"),
      pair("editorial-fashion", 2, "Source fashion portrait 2", "Editorial result 2"),
    ],
    promptVariant: {
      id: "editorial-fashion-v1",
      version: "1.0.0",
      tool: "Other AI editor",
      mode: "Image-to-image with style reference (2 inputs)",
      inputImageCount: 2,
      inputImageRoles: ["source photo", "style reference"],
      template: `${personDefaults("Editorial Fashion Look", "Professional portraits").template} Use the second image only as a fashion-style reference for wardrobe and styling.`,
      defaults: {
        ...baseDefaults,
        keepClothing: false,
        mood: "Black and white",
      },
      lastVerified: "2026-09-07",
      limitations: [
        "Needs a style reference image for best wardrobe transfer",
        "Brand logos should not be invented",
      ],
    },
  },
  {
    id: "product-studio",
    title: "Minimal Product Studio Shot",
    category: "Product and objects",
    subject: "Product or object",
    intent: "Change background",
    requirement: "One photo",
    tool: "ChatGPT Image",
    note: "Works with one isolated object",
    height: 300,
    saved: 198,
    source: "https://picsum.photos/seed/product-object-source/900/900",
    result: "https://picsum.photos/seed/minimal-product-result/900/900",
    status: "published",
    targetSourcePhoto: "One isolated object with clean edges",
    description:
      "Present one object in a minimal product studio look with clean edges and a refined background.",
    bestSourcePhoto: [
      "One main object",
      "Object fully in frame",
      "Clean visible edges",
      "Original image should not be blurry",
    ],
    changes: ["Lighting", "Background", "Color mood", "Studio finish"],
    stays: [
      "Object shape",
      "Material",
      "Brand-free details",
      "Proportions",
      "Main color",
      "Functional parts",
    ],
    examplePairs: [
      pair("product-studio", 1, "Source product", "Studio product 1"),
      pair("product-studio", 2, "Source product 2", "Studio product 2"),
    ],
    promptVariant: {
      id: "product-studio-v1",
      version: "1.0.0",
      tool: "ChatGPT Image",
      mode: "Image edit / transform with uploaded photo",
      inputImageCount: 1,
      inputImageRoles: ["source photo"],
      template: personDefaults("Minimal Product Studio Shot", "Product and objects")
        .template.replace("{{subject}}", "product or object"),
      defaults: {
        ...baseDefaults,
        background: "Minimal cream wall",
        ratio: "1:1 Square",
        keepClothing: false,
        keepPose: false,
      },
      lastVerified: "2026-09-06",
      limitations: [
        "Transparent packaging can confuse edges",
        "Busy multi-object scenes are unsupported",
      ],
    },
  },
];
